version: '3'

services:
  nginx:
    image: nginx:1.15.6-alpine
    ports:
      - 9300:80
    volumes:
      - ./public:/var/www/html/public
      - ./storage/app/public:/var/www/html/storage/app/public
      - ./docker/nginx-default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/volumes/log/nginx:/var/log/nginx
    links:
      - fpm
  fpm:
    image: cazuu/php-fpm
    volumes:
      - .:/var/www/html
      - /var/www/html/.git
      - /var/www/html/docker
      - /var/www/html/node_modules
      - /var/www/html/storage/debugbar
    links:
      - mysql
      - smtp
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: database
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 9301:3306
    volumes:
      - ./docker/volumes/mysql:/var/lib/mysql
      - ./docker/initdb.d:/docker-entrypoint-initdb.d
  #  If you use phpmyadmin, please switch out comment.
  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   environment:
  #     - PMA_ARBITRARY=1
  #     - PMA_HOST=mysql
  #     - PMA_USER=root
  #     - PMA_PASSWORD=password
  #   ports:
  #     - 9302:80
  #   volumes:
  #     - ./docker/volumes/phpmyadmin/sessions:/sessions
  #   links:
  #     - mysql
  composer:
    image: composer:1.8.4
    working_dir: /app
    entrypoint: composer
    command: --help
    volumes:
      - .:/app:cached
      - /app/.git
      - /app/docker
      - /app/node_modules
  npm:
    image: node:10.15.3
    working_dir: /app
    entrypoint: npm
    command: -h
    volumes:
      - .:/app:cached
      - /app/.git
      - /app/docker
      - /app/vendor
  smtp:
    image: schickling/mailcatcher
    ports:
      - 9303:1080